### ISSUE TITLE
CI not report second build status

### ISSUE THREAD

**Issue by nrudesu** [GNUWeeb/GNUWeebBot#8] opened 2021-03-28 15:42 UTC
# Intro 
CI not report the second pass (just one passed) when I have pull request #7 
This is normal things or CI code need improvement? 

# How to Reproduce This
simple, make a pull request

**Comment by ammarfaizi2** [comment] 2021-03-28 15:43
Related reference:
https://docs.github.com/en/rest/reference/repos#statuses

**Comment by ammarfaizi2** [comment] 2021-03-28 15:44
Could you make a dummy pull request to reproduce that?
I will clean your commit after the issue is fixed.

**Comment by nrudesu** [comment] 2021-03-28 15:50
Gocha! This what I mean : 
![image](https://user-images.githubusercontent.com/68469715/112758332-fb517800-9017-11eb-9980-16aba4049d89.png)

**Comment by ammarfaizi2** [comment] 2021-03-28 16:32
It should be fixed now, by unchecking these.

![Screenshot_2021-03-28_23-32-14](https://user-images.githubusercontent.com/26004054/112759586-dcee7b00-901d-11eb-81cb-aeeb92dffa47.png)

**Closed by ammarfaizi2** 2021-03-28 16:32 UTC
Labels: bug
